/*
 * Globalize Culture en-US
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function( window, undefined ) {

var Globalize;

if ( typeof require !== "undefined" &&
	typeof exports !== "undefined" &&
	typeof module !== "undefined" ) {
	// Assume CommonJS
	Globalize = require( "globalize" );
} else {
	// Global variable
	Globalize = window.Globalize;
}

Globalize.addCultureInfo( "en-US", "default", {
	name: "en-US",
	englishName: "English (United States)",
	calendars: {
	    standard: {
	        today: 'Today',
		    yesterday: 'Yesterday',
		    tomorrow: 'Tomorrow',
		    justNow: 'Just now',
		    oneMinuteAgo: '1 minute ago',
		    fewMinutesAgo: 'm minutes ago',
	        patterns: {
	            d: "MM/dd/yyyy",
	            D: "MMMM dd yyyy",
	            f: "MM/dd/yyyy h:mm tt",
	            F: "MMMM dd yyyy h:mm:ss tt",
	            M: "MMMM dd",
	            Y: "yyyy MMMM",

	            C1: "MM/dd h tt",
	            C2: "MM/dd",
	            C3: "d",
	            C4: "MM/yyyy",
	            C5: "h tt",
	            C6: "t",
	            C7: "hh:mmtt"
	        }
	    }
	}
});

}( this ));
