//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBabymartVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public int RecordId { get; set; }
        public string CartId { get; set; }
        public long ProductId { get; set; }
        public int Count { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual shop_bienthe shop_bienthe { get; set; }
    }
}
