//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBabymartVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class donhang_chuyenphat_tinh
    {
        public int id { get; set; }
        public Nullable<int> idtp { get; set; }
        public string tentinh { get; set; }
        public string tentinh_us { get; set; }
        public Nullable<bool> vungsau { get; set; }
        public Nullable<decimal> ship { get; set; }
    
        public virtual donhang_chuyenphat_tp donhang_chuyenphat_tp { get; set; }
    }
}
