//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBabymartVn.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class babymart_vnEntities : DbContext
    {
        public babymart_vnEntities()
            : base("name=babymart_vnEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<soft_Branches> soft_Branches { get; set; }
        public DbSet<soft_Branches_Product_Stock> soft_Branches_Product_Stock { get; set; }
        public DbSet<soft_Catalog> soft_Catalog { get; set; }
        public DbSet<soft_Channel> soft_Channel { get; set; }
        public DbSet<soft_Channel_Product_Price> soft_Channel_Product_Price { get; set; }
        public DbSet<soft_Channel_Product_SaleTotal> soft_Channel_Product_SaleTotal { get; set; }
        public DbSet<soft_Customer> soft_Customer { get; set; }
        public DbSet<soft_Order> soft_Order { get; set; }
        public DbSet<soft_Order_Child> soft_Order_Child { get; set; }
        public DbSet<soft_Product> soft_Product { get; set; }
        public DbSet<soft_Product_Variant> soft_Product_Variant { get; set; }
        public DbSet<soft_Suppliers> soft_Suppliers { get; set; }
        public DbSet<soft_Unit> soft_Unit { get; set; }
        public DbSet<sys_Employee> sys_Employee { get; set; }
        public DbSet<sys_Employee_Role> sys_Employee_Role { get; set; }
        public DbSet<sys_Role> sys_Role { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
