//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBabymartVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_rightcol
    {
        public int id { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string img { get; set; }
        public string url { get; set; }
        public Nullable<bool> hide { get; set; }
        public string alt { get; set; }
        public string title { get; set; }
    }
}
