//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBabymartVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_danhmuccon
    {
        public shop_danhmuccon()
        {
            this.shop_collection = new HashSet<shop_collection>();
            this.support_cauhoi = new HashSet<support_cauhoi>();
        }
    
        public int madanhmuccon { get; set; }
        public string grouplink { get; set; }
        public string grouplink_us { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string tendanhmuccon { get; set; }
        public string tendanhmuccon_us { get; set; }
        public Nullable<int> madanhmuc { get; set; }
        public Nullable<bool> hide { get; set; }
        public string noidung { get; set; }
        public string noidung_us { get; set; }
        public string hinhanh { get; set; }
        public string metatitle { get; set; }
        public string metakeywords { get; set; }
        public string metadescription { get; set; }
        public string metatitle_us { get; set; }
        public string metakeywords_us { get; set; }
        public string metadescription_us { get; set; }
        public string url { get; set; }
        public string url_us { get; set; }
        public string color { get; set; }
        public Nullable<int> sort { get; set; }
        public string css { get; set; }
        public Nullable<int> ma_loai { get; set; }
        public Nullable<int> uutien { get; set; }
    
        public virtual ICollection<shop_collection> shop_collection { get; set; }
        public virtual shop_danhmuc shop_danhmuc { get; set; }
        public virtual ICollection<support_cauhoi> support_cauhoi { get; set; }
    }
}
