//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBabymartVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_showhome
    {
        public shop_showhome()
        {
            this.shop_sanpham = new HashSet<shop_sanpham>();
        }
    
        public int id { get; set; }
        public string tieude { get; set; }
        public string mota { get; set; }
        public Nullable<int> get { get; set; }
    
        public virtual ICollection<shop_sanpham> shop_sanpham { get; set; }
    }
}
