//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBabymartVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_bienthe
    {
        public shop_bienthe()
        {
            this.carts = new HashSet<cart>();
            this.donhang_ct = new HashSet<donhang_ct>();
        }
    
        public long id { get; set; }
        public Nullable<int> idsp { get; set; }
        public string title { get; set; }
        public string title_us { get; set; }
        public Nullable<int> gia { get; set; }
        public Nullable<int> giasosanh { get; set; }
        public bool isdelete { get; set; }
    
        public virtual ICollection<cart> carts { get; set; }
        public virtual ICollection<donhang_ct> donhang_ct { get; set; }
        public virtual shop_sanpham shop_sanpham { get; set; }
    }
}
