//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBabymartVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_page
    {
        public int id { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string codetype { get; set; }
        public string tieude { get; set; }
        public string tieude_us { get; set; }
        public string hinhanh { get; set; }
        public string titlemenu { get; set; }
        public string noidung { get; set; }
        public string noidung_us { get; set; }
        public Nullable<System.DateTime> ngayviet { get; set; }
        public Nullable<bool> islinkout { get; set; }
        public Nullable<bool> showmenu { get; set; }
        public Nullable<bool> hide { get; set; }
        public string url { get; set; }
        public Nullable<int> sort { get; set; }
        public string metatitle { get; set; }
        public string keywords { get; set; }
        public string description { get; set; }
    }
}
