//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBabymartVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_sanpham
    {
        public shop_sanpham()
        {
            this.shop_bienthe = new HashSet<shop_bienthe>();
            this.shop_collection = new HashSet<shop_collection>();
            this.shop_image = new HashSet<shop_image>();
            this.sys_bangtin_conhang = new HashSet<sys_bangtin_conhang>();
            this.support_cauhoi = new HashSet<support_cauhoi>();
        }
    
        public int id { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string masp { get; set; }
        public Nullable<int> maloai { get; set; }
        public Nullable<int> mahieu { get; set; }
        public Nullable<int> plantype { get; set; }
        public string tensp { get; set; }
        public string tensp_us { get; set; }
        public Nullable<int> typeshowhome { get; set; }
        public string thongtin { get; set; }
        public string thongtin_us { get; set; }
        public string spurl { get; set; }
        public string spurl_us { get; set; }
        public string sptitle { get; set; }
        public string sptitle_us { get; set; }
        public string spdescription { get; set; }
        public string spdescription_us { get; set; }
        public string spkeywords_us { get; set; }
        public string spkeywords { get; set; }
        public Nullable<bool> hide { get; set; }
        public string chitiet { get; set; }
        public string chitiet_us { get; set; }
        public Nullable<int> douutien { get; set; }
        public Nullable<bool> ischeckout { get; set; }
        public Nullable<bool> ischecksaleoff { get; set; }
        public Nullable<bool> ischeckgift { get; set; }
        public string gift { get; set; }
        public Nullable<int> countsale { get; set; }
        public Nullable<System.DateTime> timeend { get; set; }
        public Nullable<double> kg { get; set; }
        public Nullable<double> chieudai { get; set; }
        public Nullable<double> chieurong { get; set; }
        public Nullable<double> chieucao { get; set; }
        public Nullable<bool> showkg { get; set; }
        public Nullable<bool> showcm { get; set; }
        public Nullable<bool> showhome { get; set; }
        public Nullable<bool> showbanner { get; set; }
        public Nullable<bool> FromSoft { get; set; }
        public Nullable<int> soft_IdGroupProduct { get; set; }
        public Nullable<int> soft_IdNPP { get; set; }
        public Nullable<int> soft_IdKho { get; set; }
        public Nullable<int> soft_IdDvt { get; set; }
        public string soft_Barcode { get; set; }
        public Nullable<int> soft_GiaTC { get; set; }
        public Nullable<int> soft_GiaM { get; set; }
    
        public virtual shop_showhome shop_showhome { get; set; }
        public virtual ICollection<shop_bienthe> shop_bienthe { get; set; }
        public virtual ICollection<shop_collection> shop_collection { get; set; }
        public virtual ICollection<shop_image> shop_image { get; set; }
        public virtual ICollection<sys_bangtin_conhang> sys_bangtin_conhang { get; set; }
        public virtual ICollection<support_cauhoi> support_cauhoi { get; set; }
        public virtual shop_thuonghieu shop_thuonghieu { get; set; }
    }
}
