//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBabymartVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_thuonghieu
    {
        public shop_thuonghieu()
        {
            this.shop_sanpham = new HashSet<shop_sanpham>();
        }
    
        public int mahieu { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string tenhieu { get; set; }
        public string tenhieu_us { get; set; }
        public string noidung { get; set; }
        public string noidung_us { get; set; }
        public string hinh { get; set; }
        public string url { get; set; }
        public Nullable<int> sort_metro { get; set; }
        public Nullable<bool> showhome { get; set; }
        public string metakeywords { get; set; }
        public string metadescription { get; set; }
        public Nullable<bool> hide { get; set; }
        public Nullable<int> maloai { get; set; }
    
        public virtual shop_loai shop_loai { get; set; }
        public virtual ICollection<shop_sanpham> shop_sanpham { get; set; }
    }
}
