//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBabymartVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_plan_saleoff
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public string OperatorOption { get; set; }
        public Nullable<int> OperatorValue { get; set; }
        public bool Visible { get; set; }
    }
}
