//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBabymartVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_danhmuc_group
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string name_us { get; set; }
        public string url { get; set; }
        public string background { get; set; }
        public string icon { get; set; }
        public Nullable<int> sort { get; set; }
        public Nullable<bool> hide { get; set; }
        public string noidung { get; set; }
    }
}
