//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBabymartVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class soft_KHO_Product
    {
        public soft_KHO_Product()
        {
            this.soft_KHO_Product_Detail = new HashSet<soft_KHO_Product_Detail>();
        }
    
        public int Id { get; set; }
        public int IdKho { get; set; }
        public int IdNPP { get; set; }
        public int Total { get; set; }
        public System.DateTime Date { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<soft_KHO_Product_Detail> soft_KHO_Product_Detail { get; set; }
    }
}
