//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBabymartVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class soft_Order
    {
        public soft_Order()
        {
            this.soft_Order_Child = new HashSet<soft_Order_Child>();
        }
    
        public long Id { get; set; }
        public Nullable<int> Id_From { get; set; }
        public Nullable<int> Id_To { get; set; }
        public int Status { get; set; }
        public Nullable<double> Total { get; set; }
        public string Note { get; set; }
        public Nullable<int> TypeOrder { get; set; }
        public Nullable<bool> IsShip { get; set; }
        public int EmployeeCreate { get; set; }
        public System.DateTime DateCreate { get; set; }
        public Nullable<int> EmployeeUpdate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
    
        public virtual ICollection<soft_Order_Child> soft_Order_Child { get; set; }
    }
}
