//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBabymartVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class soft_Branches
    {
        public soft_Branches()
        {
            this.soft_Branches_Product_Stock = new HashSet<soft_Branches_Product_Stock>();
            this.soft_Channel = new HashSet<soft_Channel>();
        }
    
        public int BranchesId { get; set; }
        public string BranchesName { get; set; }
        public string Note { get; set; }
        public int Type { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<int> EmployeeCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<int> EmployeeUpdate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
    
        public virtual ICollection<soft_Branches_Product_Stock> soft_Branches_Product_Stock { get; set; }
        public virtual ICollection<soft_Channel> soft_Channel { get; set; }
    }
}
