//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBabymartVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class soft_group_customer_product
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> BanleCH { get; set; }
        public Nullable<int> Online { get; set; }
        public Nullable<int> Si { get; set; }
        public Nullable<int> Lazada { get; set; }
        public Nullable<int> Shopee { get; set; }
        public Nullable<int> Mymall { get; set; }
        public Nullable<System.DateTime> Date_Onl { get; set; }
        public Nullable<int> Chietkhau_Onl { get; set; }
        public Nullable<System.DateTime> Date_CH { get; set; }
        public Nullable<int> Chietkhau_CH { get; set; }
    }
}
