//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBabymartVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class soft_Channel_Product_Price
    {
        public soft_Channel_Product_Price()
        {
            this.soft_Channel_Product_SaleTotal = new HashSet<soft_Channel_Product_SaleTotal>();
        }
    
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int ChannelId { get; set; }
        public int Price { get; set; }
        public string Note { get; set; }
        public int EmployeeCreate { get; set; }
        public System.DateTime DateCreate { get; set; }
        public Nullable<int> EmployeeUpdate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
    
        public virtual soft_Channel soft_Channel { get; set; }
        public virtual ICollection<soft_Channel_Product_SaleTotal> soft_Channel_Product_SaleTotal { get; set; }
        public virtual soft_Product soft_Product { get; set; }
    }
}
