//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBabymartVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class soft_KHO
    {
        public int Id { get; set; }
        public string Kho { get; set; }
        public string Diachi { get; set; }
        public string Lienhe { get; set; }
        public string Makho { get; set; }
    }
}
