//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBabymartVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class soft_Channel
    {
        public soft_Channel()
        {
            this.soft_Channel_Product_Price = new HashSet<soft_Channel_Product_Price>();
            this.sys_Role = new HashSet<sys_Role>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Channel { get; set; }
        public Nullable<int> BranchesId { get; set; }
        public string Note { get; set; }
        public int Type { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public int EmployeeCreate { get; set; }
        public System.DateTime DateCreate { get; set; }
        public string EmployeeUpdate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
    
        public virtual soft_Branches soft_Branches { get; set; }
        public virtual ICollection<soft_Channel_Product_Price> soft_Channel_Product_Price { get; set; }
        public virtual ICollection<sys_Role> sys_Role { get; set; }
    }
}
