//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBabymartVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class soft_Product_Variant
    {
        public long id { get; set; }
        public Nullable<int> idsp { get; set; }
        public string title { get; set; }
        public string title_us { get; set; }
        public Nullable<int> gia { get; set; }
        public Nullable<int> giasosanh { get; set; }
        public bool isdelete { get; set; }
        public Nullable<int> soft_gianhap { get; set; }
        public Nullable<int> soft_gianhapcu { get; set; }
        public Nullable<int> soft_gianhapmoi { get; set; }
        public Nullable<int> soft_soluongton { get; set; }
    }
}
