//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBabymartVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class soft_KHO_Order_Child
    {
        public int Id { get; set; }
        public int IdOrder { get; set; }
        public int IdProduct { get; set; }
        public int IdNPP { get; set; }
        public Nullable<int> Total_Day { get; set; }
        public Nullable<int> Total_Product { get; set; }
        public Nullable<int> Total_Order { get; set; }
        public Nullable<double> Total_Money { get; set; }
        public string Note { get; set; }
    }
}
