//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBabymartVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class soft_KHO_Product_Detail
    {
        public int Id { get; set; }
        public int Id_kho_product { get; set; }
        public long IdProduct { get; set; }
        public int SL { get; set; }
        public int Price { get; set; }
    
        public virtual soft_KHO_Product soft_KHO_Product { get; set; }
    }
}
