//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBabymartVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class soft_Channel_Product_SaleTotal
    {
        public System.DateTime DateSale { get; set; }
        public int Channel_Product_Id { get; set; }
        public Nullable<int> Total_sale { get; set; }
    
        public virtual soft_Channel_Product_Price soft_Channel_Product_Price { get; set; }
    }
}
