//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBabymartVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class soft_KHO_Order
    {
        public int Id { get; set; }
        public string Note { get; set; }
        public System.DateTime DateOrder { get; set; }
        public Nullable<double> Total { get; set; }
    }
}
