//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBabymartVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class support_cauhoi
    {
        public int mach { get; set; }
        public string cauhoi { get; set; }
        public string traloi { get; set; }
        public string nguon { get; set; }
        public Nullable<int> maloai { get; set; }
        public Nullable<int> ma_hieu { get; set; }
        public Nullable<int> ma_sp { get; set; }
    
        public virtual shop_danhmuccon shop_danhmuccon { get; set; }
        public virtual shop_sanpham shop_sanpham { get; set; }
    }
}
