//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBabymartVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_tags_Ref
    {
        public int Id { get; set; }
        public Nullable<int> RefId { get; set; }
        public Nullable<int> RefTag { get; set; }
        public Nullable<int> RefCollection { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> TypeCollection { get; set; }
    
        public virtual sys_tags_Summary sys_tags_Summary { get; set; }
    }
}
