//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBabymartVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_content
    {
        public int Id { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string Name_us { get; set; }
        public string Contents { get; set; }
        public string Contents_us { get; set; }
        public Nullable<bool> hide { get; set; }
    }
}
