//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBabymartVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_tags_Summary
    {
        public sys_tags_Summary()
        {
            this.sys_tags_Ref = new HashSet<sys_tags_Ref>();
        }
    
        public int Id { get; set; }
        public string Tags { get; set; }
        public Nullable<int> RefType { get; set; }
    
        public virtual ICollection<sys_tags_Ref> sys_tags_Ref { get; set; }
    }
}
