//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBabymartVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_bangtin_conhang
    {
        public int id { get; set; }
        public Nullable<int> nguoinhanbangtin { get; set; }
        public Nullable<int> idsp { get; set; }
    
        public virtual shop_sanpham shop_sanpham { get; set; }
        public virtual sys_nhanbangtin sys_nhanbangtin { get; set; }
    }
}
