//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftBabymartVn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_file
    {
        public int Id { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string Files { get; set; }
        public string Files_us { get; set; }
        public int type { get; set; }
        public string link { get; set; }
        public Nullable<bool> hide { get; set; }
        public Nullable<int> sort { get; set; }
    }
}
